spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
    name: microconfig-test-client2

eureka:
  client:
    service-url:
      defaultZone: http://admin:zhangxin@localhost:7001/eureka
      
info:
  app.name: microcloud-config-client-dev
  company.name: zhangxin333333333
  
---
server:
  port: 8102

spring:
  profiles: beta
  application:
    name: microconfig-test-client2

eureka:
  client:
    service-url:
      defaultZone: http://admin:zhangxin@localhost:7001/eureka
      
info:
  app.name: microcloud-config-client-dev
  company.name: zhangxin
